---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by z1178.
--- DateTime: 01/11/2022 10:57
---

local _M = { version = 1.0 }
function _M.testFunction()
    print("Test function")
end

return _M